### ISSUE TITLE
Correction for green-900 tone

### ISSUE THREAD

**Issue by psantos9** [ValentinGot/material-design-colors#1]
Hi,
the green-900 color is not correct in your scss and less files.
You have #b71c1c (red-900) and it should be #1b5e20.

Thanks for your work, btw!

**Comment by ValentinGot** [comment]
Hi,

Indeed, i'm on it :)

**Comment by ValentinGot** [comment]
Done, you can update to 1.0.2 to get the fix :)

**Comment by psantos9** [comment]
Thanks!
